const categories = [
  {
    id: "bread",
    name: "Quick Bread",
    endpoint: "/bread",
    title: "Whole-Grain Banana Bread",
    img: "/img/tomato.avif",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "burger",
    name: "burger",
    endpoint: "/burger",
    img: "/img/burger.avif",
    title: "Burger",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "tomato",
    name: "tomato",
    endpoint: "/tomato",
    img: "/img/bread.avif",
    title: "Tomato basil",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "bread2",
    name: "Bread",
    endpoint: "/bread",
    img: "/img/tomato.avif",
    title: "Bread",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "burger2",
    name: "burger",
    endpoint: "/burger",
    img: "/img/burger.avif",
    title: "Burger",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "tomato2",
    name: "tomato",
    endpoint: "/tomato",
    img: "/img/bread.avif",
    title: "Tomato basil",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "bread3",
    name: "Bread",
    endpoint: "/bread",
    img: "/img/tomato.avif",
    title: "Bread",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "burger3",
    name: "burger",
    endpoint: "/burger",
    img: "/img/burger.avif",
    title: "Burger",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "tomato3",
    name: "tomato",
    endpoint: "/tomato",
    img: "/img/bread.avif",
    title: "Tomato basil",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "bread4",
    name: "Bread",
    endpoint: "/bread",
    img: "/img/tomato.avif",
    title: "Bread",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "burger4",
    name: "burger",
    endpoint: "/burger",
    img: "/img/burger.avif",
    title: "Burger",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "tomato4",
    name: "tomato",
    endpoint: "/tomato",
    img: "/img/bread.avif",
    title: "Tomato basil",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "bread5",
    name: "Bread",
    endpoint: "/bread",
    img: "/img/tomato.avif",
    title: "Bread",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "burger5",
    name: "burger",
    endpoint: "/burger",
    img: "/img/burger.avif",
    title: "Burger",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
  {
    id: "tomato5",
    name: "tomato",
    endpoint: "/tomato",
    img: "/img/bread.avif",
    title: "Tomato basil",
    description:
      "This one-bowl banana bread - our 2018 Recipe of the Year - uses the simplest ingredients, but is incredibly moist and flavorful. While the recipe calls for a 50/50 mix of flours (all-purpose and whole wheat), we often make the bread 100% whole wheat, and honestly? No one can tell, it's that good! And not only is this bread delicious - it's versatile.",
    prep: "10 mins",
    brake: "1 hr to 1 hr 15 mins",
    total: "1 hr 10 mins",
    profit: "1 loaf, 12 generous servings",
  },
];
export default function handler(req, res) {
  res.status(200).json(categories);
}
